#ifndef SIO_DOIP_ERR_H_
#define SIO_DOIP_ERR_H_

enum sio_doip_err
{
    SIO_DOIP_ERR_ROUTE_REJECT_UNKOWNSA,
    SIO_DOIP_ERR_ROUTE_REJECT_REPEAT,
    SIO_DOIP_ERR_ROUTE_REJECT_DIFFSA,
    SIO_DOIP_ERR_ROUTE_OK
};

#endif